sudo: false

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

language: scala

script:
  - sbt g8 g8Test

scala:
  - 2.12.10
  - 2.11.8

# whitelist
branches:
  only:
    - master
